# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker


trigger:
  branches:
    include:
      - $(branchName)
    exclude:
      - '*'


  


resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  repository: '$(imageRepository)'
  dockerRegistryName: '$(ACR)'
  dockerRegistryServiceConnection: '$(ACRSC1)'
  dockerfilePath: $(Build.SourcesDirectory)/Dockerfile
  prefix: '$(tagPrefix)'
  BuildID: '$(Build.BuildId)'
  Webap: '$(Webapp-Name)'
  Resource_group: '$(Resource_group_name)'
  branchName: ''
  
  
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImageName: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build and push an image to container registry'
      inputs:
       command: 'buildAndPush'
       containerRegistry: 'ACRSC'  # Specify the name of your Docker registry service connection here
       repository: '$(repository)'  # Update this line to use the correct variables
       dockerfile: '$(dockerfilePath)'
       tags: '$(prefix)-$(BuildID)'






      
