# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker


trigger:
  branches:
    include:
    - main
pr:
  branches:
    exclude:
    - '*' 


  


resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  repository: '$(imageRepository)'
  dockerRegistryName: '$(ACR)'
  dockerRegistryServiceConnection: '$(ACRSC1)'
  dockerfilePath: $(Build.SourcesDirectory)/Dockerfile
  prefix: '$(tagPrefix)'
  BuildID: '$(Build.BuildId)'
  Webap: '$(Webapp-Name)'
  Resource_group: '$(Resource_group_name)'
  branchName: ''
  
  
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: 'Build and push an image to container registry'
      inputs:
       command: 'buildAndPush'
       containerRegistry: 'ACRSC'  # Specify the name of your Docker registry service connection here
       repository: '$(repository)'  # Update this line to use the correct variables
       dockerfile: '$(dockerfilePath)'
       tags: '$(prefix)-$(BuildID)'

- stage: Deploy
  displayName: Deploy to App Service
  dependsOn: Build
  jobs:
    - job: Deploy
      displayName: Deploy
      steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: ServiceConnection_Manual
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              # Azure CLI commands to log in, configure ACR login, and deploy image
              

              az acr login --name '$(dockerRegistryName)' --username '$(dockerRegistryName)' --password '$(dockerRegistryServiceConnection)'
              
              az webapp config container set --name '$(Webap)' --resource-group '$(Resource_group)' --docker-custom-image-name '$(dockerRegistryName)'/'$(Webap)':'$(prefix)' --docker-registry-server-url https://'$(dockerRegistryName)'.azurecr.io
              # Restart the App Service
              az webapp restart --ids $/subscriptions/e55321d2-e142-42d7-ae35-c2257f7aabc1/resourceGroups/'$(Resource_group)'/providers/Microsoft.Web/sites/'$(Webap)'
              arguments: 'some_variable'





      
